### PR TITLE
Fix path

### PR DESCRIPTION
**Pull request by xxxxlr**

### CODE REVIEW

**Comment by neroniaky** [comment]
Hi @xxxxlr, thanks for your PR.
The path links to `lib` which has the compiled files and not the source files. It gets created when you run `npm run build` and is part of the npm-package.
Could you explain to me why changing this makes sense? Thank you!

**Comment by xxxxlr** [comment]
Hey neroniaky,
You are definitely right if package consumers are installing it from NPM registry.
For some case when the package is under active dev, users might need to install it from github for the latest version if NPM is not published yet. However this might just be a rare case. I am cool if you want to close it.

I also tried npm run build locally from the package, but the tsc is not creating the lib folder. Do you have any insight about why?

Thanks for the package! Saving me a lot of time!

**Comment by neroniaky** [comment]
Thanks for the explanation. I think that's a good point, but I'm not 100% sure how to handle it best. If I leave the ./lib in place I have to commit the compiled files to Github too. If I change it to ./src users of the NPM Package would access the non-compiled files too. Do you have any suggestions how to solve this?

I tried to run `npm run build` on a fresh clone and it completed without any issues. Here's what I did:
```bash
git clone https://github.com/neroniaky/angular2-token.git
cd angular2-token
npm i
npm run build
```
Did it give you any errors?

**Comment by xxxxlr** [comment]
Thanks for the instructions! Now I am able to generate the ./lib with build. I was missing ```$ npm i ``` before running build.

I don't know a better way to handle it as well. But I think being a bit bias to NPM might be more stable which is what you are doing now.

If we can have mention it in the README with a dev section it might be enough. Or maybe a git push hook to publish automatically when pushing it  to a stable branch.

**Comment by neroniaky** [comment]
Closing because #10.

**Pull request closed without merging**
