### PR TITLE
Custom Login Field

### PR DESCRIPTION
**Pull request by brunoluigi**
Added the ability to setup a custom login field other than email.
Added loginField to default options with value 'email'.
Updated SignInData interface to accept login instead of email attribute.
Updated Angular2TokenService to use loginField option to send auth info to server.

### CODE REVIEW

**Comment by brunoluigi** [comment]
Haven't changed the login field for register, password recovery, etc due to some design doubts, what you guys think is the best way to treat a custom login field in these scenarios?

**Comment by NiekPas** [comment]
Having a non-email login option makes sense, but be aware that this breaks compatibility with the default configuration for `devise_token_auth`, since its `User` model requires an `email` attribute.

Since going with `devise_token_auth` is pretty much the default option, it might be wise to add a link to [this devise_token_auth doc page](https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-sign-in-with-something-other-than-their-email-address) to the `angular-token` docs.

**Comment by arjenbrandenburgh** [comment]
This functionality has been added to version 6.0.0-rc.1. It defaults to `email` obviously.

Please read the [Configuration Guide](https://github.com/neroniaky/angular2-token/wiki/Configuration) for the `loginField`.

**Comment by NiekPas** [comment]
I should've explained more clearly. It breaks compatibility because [the registerAccount method](https://github.com/brunoluigi/angular2-token/blob/2d5dd013460badf1f18b40a1c5ca26a0717d0f90/src/angular2-token.service.ts#L155) does not take into account the value of loginField ([the way the signIn method does](https://github.com/brunoluigi/angular2-token/blob/2d5dd013460badf1f18b40a1c5ca26a0717d0f90/src/angular2-token.service.ts#L186)), and just [sends a stringified `registerData` object](https://github.com/brunoluigi/angular2-token/blob/2d5dd013460badf1f18b40a1c5ca26a0717d0f90/src/angular2-token.service.ts#L169), which has a login property, not an email property.

**Comment by arjenbrandenburgh** [comment]
I agree. But I assume that if someone asks for this functionality, they are aware of the implications.

**Comment by NiekPas** [comment]
Is it possible to update the registerAccount method to match the signIn method? Something like this:

    let body = JSON.stringify({
      password_confirmation:          registerData.passwordConfirmation,
      confirm_success_url:            this.atOptions.registerAccountCallback,
      [this.atOptions.loginField]:    registerData.login,
      password:                       registerData.password,
      name:                           registerData.name,
      userType:                       registerData.userType
    });

    return this.post(this.getUserPath() + this.atOptions.registerAccountPath, body);

**Pull request closed without merging**
