### PR TITLE
Fixed not refreshing atCurrentAuthData problem.

### PR DESCRIPTION
**Pull request by volpejoaquin**
https://github.com/neroniaky/angular2-token/issues/260

### CODE REVIEW

**Comment by neroniaky** [comment]
@volpejoaquin thanks

**Comment by volpejoaquin** [comment]
@neroniaky Could you tell me when you will add the new tag with this fix ?. I need update your library on my proyect and I need the last version of the code.

**Comment by volpejoaquin** [comment]
@neroniaky some news related to the tag ? :)

**Comment by nolancaster** [comment]
@neroniaky  Any chance we could an npm release with this fix at some point?

**Pull request merged**
