### PR TITLE
[fix] isLoggedIn method

### PR DESCRIPTION
**Pull request by malina**
This method check logged user or not.

On init we call method _getAuthDataFromStorage().
And if in localstorage has data, then _currentAuthData not null.
So we can use tokenService.isLoggedIn in canActivate:

```
import { Injectable } from '@angular/core';
import { CanActivate, Router, ActivatedRouteSnapshot, RouterStateSnapshot } from '@angular/router';

import { Angular2TokenService } from 'angular2-token';

@Injectable()
export class CanActivateViaAuthGuard implements CanActivate {

  constructor(private authService: Angular2TokenService, private router: Router) {
  }

  canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): any {
    if (this.authService.isLoggedIn) {
      return true;
    } else {
      this.router.navigate(['/login']);
      return false;
    }
  }
}
```

(sorry for my english)

### CODE REVIEW

**Comment by neroniaky** [comment]
Hi @malina, thanks for your PR. 
Could you reiterate in which case you would need this function and can't use the Service directly for CanActivate? Thank you! Example:

```javascript
const routerConfig: Routes = [
    { 
        path: '', 
        component: PublicComponent 
    }, {
        path: 'restricted', 
        component: RestrictedComponent, 
        canActivate: [Angular2TokenService] 
    }
];
```

**Comment by diegoh** [comment]
This might be related to #24, redirecting a logged out user.
Another example could be deleting local storage like items like a device token if the user is logged out.

**Comment by artem-galas** [comment]
I didn't get why he added this method `isLoggedIn`. 
I think the best solution would be to change `canActivate` method the following way:

```javascript
canActivate() {
    if (this._currentUserData)
        return true;
    else {
        this.router.navigate(['/sign-in']); // <- maybe use this path from config
        return false;
    }
}
```

**Comment by artem-galas** [comment]
I guess I understood why we need this method. When loading the first time we get null in `this._tokenService.currentUserData`, and this method should prevent this.

**Comment by malina** [comment]
@artem-galas exactly

**Comment by neroniaky** [comment]
Hey @malina, I added a signedIn method with commit [b4b515c](https://github.com/neroniaky/angular2-token/commit/b4b515c06c3292c926aee8ee6e487442a1e5405f) like you suggested.

Thanks a lot for your input! 👍

**Pull request closed without merging**
