### PR TITLE
clear only angular2-token items from localStorage

### PR DESCRIPTION
**Pull request by sgruhier**
instead of clearing all localStorage data

### CODE REVIEW

**Comment by sgruhier** [comment]
For a better UX, it's always better to redirect to requested URL. for example if you share a link by email. 
If you are fine with it, I'll add unit tests.
Thanks

**Comment by sgruhier** [comment]
damned I did 2 PR but they are merged :(

**Comment by neroniaky** [comment]
Hey @sgruhier thanks a lot for your PR. Especially the selective clear of the local storage make a lot of sense. Gonna try to commit the changes myself today.

**Comment by sgruhier** [comment]
great if you have any issues, let me know, I'll make branches and 2 separated PR. Only look at the 2 first commits 9c48926 and d19d703

**Comment by neroniaky** [comment]
@sgruhier I just committed your first commit of this PR. Would be great if you could make your second commit a branch.

**Comment by sgruhier** [comment]
sure, I'm doing it now. you can close that PR

**Pull request closed without merging**
