### PR TITLE
additionalData for login and register

### PR DESCRIPTION
**Pull request by acegilz**
additionalData for login and register

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

additionalData for login and register requests (Allows Implement Recaptcha or 2Auth)

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?
[ ] Yes
[X] No

### CODE REVIEW

**Comment by acegilz** [comment]
Only for the registration? The login you think is fine as it is?

**Comment by neroniaky** [comment]
Hey @acegilz, I talked to @arjenbrandenburgh and we agree that your additionalData approach is the better one. I don’t think the check against undefined is really necessary in this case. Could you remove those, then I’ll merge. Thanks!

**Comment by acegilz** [comment]
> Hey @acegilz, I talked to @arjenbrandenburgh and we agree that your additionalData approach is the better one. I don’t think the check against undefined is really necessary in this case. Could you remove those, then I’ll merge. Thanks!

Without the comparison with the undefined, the automation tests fail.

Please tell me how we should proceed.

**Comment by acegilz** [comment]
Hello,

Is there update regarding this?

**Comment by acegilz** [comment]
Hello,

Is there update regarding this?

**Comment by neroniaky** [comment]
Sorry for the late answer. You're right, let's keep the check for undefined for now. Would be nice if you could change it back. Thank you!

**Comment by acegilz** [comment]
Hello, 

When are you planning to include this feature in the NPM package?
Until you do it, what is the simplest way to use this change?

Thanks

**Comment by acegilz** [comment]
@neroniaky I don't understand why this only appears on the 7.1.0RC (not in the npm)
but appears on the committed files of the 7.0.1

**Pull request merged**
